on:
   push:
     branches:
       - master
permissions:
  contents: write
  issues: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          # package-name: cliui
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      - run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: npm run compile
      # - name: push Deno release
      #   run: |
      #     git config user.name github-actions[bot]
      #     git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      #     git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/yargs/cliui.git"
      #     git checkout -b deno
      #     git add -f build
      #     git commit -a -m 'chore: ${{ steps.release.outputs.tag_name }} release'
      #     git push origin +deno
      #     git tag -a ${{ steps.release.outputs.tag_name }}-deno -m 'chore: ${{ steps.release.outputs.tag_name }} release'
      #     git push origin ${{ steps.release.outputs.tag_name }}-deno
      #   if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          registry-url: 'https://external-dot-oss-automation.appspot.com/'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #   if: ${{ steps.release.outputs.release_created }}

